# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/smiller53/tmp/streamvbyte

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/smiller53/tmp/streamvbyte

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/Applications/CMake.app/Contents/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/smiller53/tmp/streamvbyte/CMakeFiles /Users/smiller53/tmp/streamvbyte//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/smiller53/tmp/streamvbyte/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named streamvbyte_static

# Build rule for target.
streamvbyte_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 streamvbyte_static
.PHONY : streamvbyte_static

# fast build rule for target.
streamvbyte_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/build
.PHONY : streamvbyte_static/fast

#=============================================================================
# Target rules for targets named streamvbyte

# Build rule for target.
streamvbyte: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 streamvbyte
.PHONY : streamvbyte

# fast build rule for target.
streamvbyte/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/build
.PHONY : streamvbyte/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named shane

# Build rule for target.
shane: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shane
.PHONY : shane

# fast build rule for target.
shane/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane.dir/build.make CMakeFiles/shane.dir/build
.PHONY : shane/fast

#=============================================================================
# Target rules for targets named shane1

# Build rule for target.
shane1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shane1
.PHONY : shane1

# fast build rule for target.
shane1/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane1.dir/build.make CMakeFiles/shane1.dir/build
.PHONY : shane1/fast

#=============================================================================
# Target rules for targets named shane2

# Build rule for target.
shane2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shane2
.PHONY : shane2

# fast build rule for target.
shane2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane2.dir/build.make CMakeFiles/shane2.dir/build
.PHONY : shane2/fast

#=============================================================================
# Target rules for targets named perf

# Build rule for target.
perf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 perf
.PHONY : perf

# fast build rule for target.
perf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perf.dir/build.make CMakeFiles/perf.dir/build
.PHONY : perf/fast

#=============================================================================
# Target rules for targets named writeseq

# Build rule for target.
writeseq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 writeseq
.PHONY : writeseq

# fast build rule for target.
writeseq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/writeseq.dir/build.make CMakeFiles/writeseq.dir/build
.PHONY : writeseq/fast

#=============================================================================
# Target rules for targets named unit

# Build rule for target.
unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unit
.PHONY : unit

# fast build rule for target.
unit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit.dir/build.make CMakeFiles/unit.dir/build
.PHONY : unit/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

example.o: example.c.o
.PHONY : example.o

# target to build an object file
example.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.o
.PHONY : example.c.o

example.i: example.c.i
.PHONY : example.i

# target to preprocess a source file
example.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.i
.PHONY : example.c.i

example.s: example.c.s
.PHONY : example.s

# target to generate assembly for a file
example.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.s
.PHONY : example.c.s

shane.o: shane.c.o
.PHONY : shane.o

# target to build an object file
shane.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane.dir/build.make CMakeFiles/shane.dir/shane.c.o
.PHONY : shane.c.o

shane.i: shane.c.i
.PHONY : shane.i

# target to preprocess a source file
shane.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane.dir/build.make CMakeFiles/shane.dir/shane.c.i
.PHONY : shane.c.i

shane.s: shane.c.s
.PHONY : shane.s

# target to generate assembly for a file
shane.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane.dir/build.make CMakeFiles/shane.dir/shane.c.s
.PHONY : shane.c.s

shane1.o: shane1.c.o
.PHONY : shane1.o

# target to build an object file
shane1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane1.dir/build.make CMakeFiles/shane1.dir/shane1.c.o
.PHONY : shane1.c.o

shane1.i: shane1.c.i
.PHONY : shane1.i

# target to preprocess a source file
shane1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane1.dir/build.make CMakeFiles/shane1.dir/shane1.c.i
.PHONY : shane1.c.i

shane1.s: shane1.c.s
.PHONY : shane1.s

# target to generate assembly for a file
shane1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane1.dir/build.make CMakeFiles/shane1.dir/shane1.c.s
.PHONY : shane1.c.s

shane2.o: shane2.c.o
.PHONY : shane2.o

# target to build an object file
shane2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane2.dir/build.make CMakeFiles/shane2.dir/shane2.c.o
.PHONY : shane2.c.o

shane2.i: shane2.c.i
.PHONY : shane2.i

# target to preprocess a source file
shane2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane2.dir/build.make CMakeFiles/shane2.dir/shane2.c.i
.PHONY : shane2.c.i

shane2.s: shane2.c.s
.PHONY : shane2.s

# target to generate assembly for a file
shane2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shane2.dir/build.make CMakeFiles/shane2.dir/shane2.c.s
.PHONY : shane2.c.s

src/streamvbyte_0124_decode.o: src/streamvbyte_0124_decode.c.o
.PHONY : src/streamvbyte_0124_decode.o

# target to build an object file
src/streamvbyte_0124_decode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_0124_decode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_0124_decode.c.o
.PHONY : src/streamvbyte_0124_decode.c.o

src/streamvbyte_0124_decode.i: src/streamvbyte_0124_decode.c.i
.PHONY : src/streamvbyte_0124_decode.i

# target to preprocess a source file
src/streamvbyte_0124_decode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_0124_decode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_0124_decode.c.i
.PHONY : src/streamvbyte_0124_decode.c.i

src/streamvbyte_0124_decode.s: src/streamvbyte_0124_decode.c.s
.PHONY : src/streamvbyte_0124_decode.s

# target to generate assembly for a file
src/streamvbyte_0124_decode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_0124_decode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_0124_decode.c.s
.PHONY : src/streamvbyte_0124_decode.c.s

src/streamvbyte_0124_encode.o: src/streamvbyte_0124_encode.c.o
.PHONY : src/streamvbyte_0124_encode.o

# target to build an object file
src/streamvbyte_0124_encode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_0124_encode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_0124_encode.c.o
.PHONY : src/streamvbyte_0124_encode.c.o

src/streamvbyte_0124_encode.i: src/streamvbyte_0124_encode.c.i
.PHONY : src/streamvbyte_0124_encode.i

# target to preprocess a source file
src/streamvbyte_0124_encode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_0124_encode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_0124_encode.c.i
.PHONY : src/streamvbyte_0124_encode.c.i

src/streamvbyte_0124_encode.s: src/streamvbyte_0124_encode.c.s
.PHONY : src/streamvbyte_0124_encode.s

# target to generate assembly for a file
src/streamvbyte_0124_encode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_0124_encode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_0124_encode.c.s
.PHONY : src/streamvbyte_0124_encode.c.s

src/streamvbyte_decode.o: src/streamvbyte_decode.c.o
.PHONY : src/streamvbyte_decode.o

# target to build an object file
src/streamvbyte_decode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_decode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_decode.c.o
.PHONY : src/streamvbyte_decode.c.o

src/streamvbyte_decode.i: src/streamvbyte_decode.c.i
.PHONY : src/streamvbyte_decode.i

# target to preprocess a source file
src/streamvbyte_decode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_decode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_decode.c.i
.PHONY : src/streamvbyte_decode.c.i

src/streamvbyte_decode.s: src/streamvbyte_decode.c.s
.PHONY : src/streamvbyte_decode.s

# target to generate assembly for a file
src/streamvbyte_decode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_decode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_decode.c.s
.PHONY : src/streamvbyte_decode.c.s

src/streamvbyte_encode.o: src/streamvbyte_encode.c.o
.PHONY : src/streamvbyte_encode.o

# target to build an object file
src/streamvbyte_encode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_encode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_encode.c.o
.PHONY : src/streamvbyte_encode.c.o

src/streamvbyte_encode.i: src/streamvbyte_encode.c.i
.PHONY : src/streamvbyte_encode.i

# target to preprocess a source file
src/streamvbyte_encode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_encode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_encode.c.i
.PHONY : src/streamvbyte_encode.c.i

src/streamvbyte_encode.s: src/streamvbyte_encode.c.s
.PHONY : src/streamvbyte_encode.s

# target to generate assembly for a file
src/streamvbyte_encode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_encode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_encode.c.s
.PHONY : src/streamvbyte_encode.c.s

src/streamvbyte_zigzag.o: src/streamvbyte_zigzag.c.o
.PHONY : src/streamvbyte_zigzag.o

# target to build an object file
src/streamvbyte_zigzag.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_zigzag.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_zigzag.c.o
.PHONY : src/streamvbyte_zigzag.c.o

src/streamvbyte_zigzag.i: src/streamvbyte_zigzag.c.i
.PHONY : src/streamvbyte_zigzag.i

# target to preprocess a source file
src/streamvbyte_zigzag.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_zigzag.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_zigzag.c.i
.PHONY : src/streamvbyte_zigzag.c.i

src/streamvbyte_zigzag.s: src/streamvbyte_zigzag.c.s
.PHONY : src/streamvbyte_zigzag.s

# target to generate assembly for a file
src/streamvbyte_zigzag.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbyte_zigzag.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbyte_zigzag.c.s
.PHONY : src/streamvbyte_zigzag.c.s

src/streamvbytedelta_decode.o: src/streamvbytedelta_decode.c.o
.PHONY : src/streamvbytedelta_decode.o

# target to build an object file
src/streamvbytedelta_decode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbytedelta_decode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbytedelta_decode.c.o
.PHONY : src/streamvbytedelta_decode.c.o

src/streamvbytedelta_decode.i: src/streamvbytedelta_decode.c.i
.PHONY : src/streamvbytedelta_decode.i

# target to preprocess a source file
src/streamvbytedelta_decode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbytedelta_decode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbytedelta_decode.c.i
.PHONY : src/streamvbytedelta_decode.c.i

src/streamvbytedelta_decode.s: src/streamvbytedelta_decode.c.s
.PHONY : src/streamvbytedelta_decode.s

# target to generate assembly for a file
src/streamvbytedelta_decode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbytedelta_decode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbytedelta_decode.c.s
.PHONY : src/streamvbytedelta_decode.c.s

src/streamvbytedelta_encode.o: src/streamvbytedelta_encode.c.o
.PHONY : src/streamvbytedelta_encode.o

# target to build an object file
src/streamvbytedelta_encode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbytedelta_encode.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbytedelta_encode.c.o
.PHONY : src/streamvbytedelta_encode.c.o

src/streamvbytedelta_encode.i: src/streamvbytedelta_encode.c.i
.PHONY : src/streamvbytedelta_encode.i

# target to preprocess a source file
src/streamvbytedelta_encode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbytedelta_encode.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbytedelta_encode.c.i
.PHONY : src/streamvbytedelta_encode.c.i

src/streamvbytedelta_encode.s: src/streamvbytedelta_encode.c.s
.PHONY : src/streamvbytedelta_encode.s

# target to generate assembly for a file
src/streamvbytedelta_encode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte_static.dir/build.make CMakeFiles/streamvbyte_static.dir/src/streamvbytedelta_encode.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/streamvbyte.dir/build.make CMakeFiles/streamvbyte.dir/src/streamvbytedelta_encode.c.s
.PHONY : src/streamvbytedelta_encode.c.s

tests/perf.o: tests/perf.c.o
.PHONY : tests/perf.o

# target to build an object file
tests/perf.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perf.dir/build.make CMakeFiles/perf.dir/tests/perf.c.o
.PHONY : tests/perf.c.o

tests/perf.i: tests/perf.c.i
.PHONY : tests/perf.i

# target to preprocess a source file
tests/perf.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perf.dir/build.make CMakeFiles/perf.dir/tests/perf.c.i
.PHONY : tests/perf.c.i

tests/perf.s: tests/perf.c.s
.PHONY : tests/perf.s

# target to generate assembly for a file
tests/perf.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/perf.dir/build.make CMakeFiles/perf.dir/tests/perf.c.s
.PHONY : tests/perf.c.s

tests/unit.o: tests/unit.c.o
.PHONY : tests/unit.o

# target to build an object file
tests/unit.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit.dir/build.make CMakeFiles/unit.dir/tests/unit.c.o
.PHONY : tests/unit.c.o

tests/unit.i: tests/unit.c.i
.PHONY : tests/unit.i

# target to preprocess a source file
tests/unit.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit.dir/build.make CMakeFiles/unit.dir/tests/unit.c.i
.PHONY : tests/unit.c.i

tests/unit.s: tests/unit.c.s
.PHONY : tests/unit.s

# target to generate assembly for a file
tests/unit.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/unit.dir/build.make CMakeFiles/unit.dir/tests/unit.c.s
.PHONY : tests/unit.c.s

tests/writeseq.o: tests/writeseq.c.o
.PHONY : tests/writeseq.o

# target to build an object file
tests/writeseq.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/writeseq.dir/build.make CMakeFiles/writeseq.dir/tests/writeseq.c.o
.PHONY : tests/writeseq.c.o

tests/writeseq.i: tests/writeseq.c.i
.PHONY : tests/writeseq.i

# target to preprocess a source file
tests/writeseq.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/writeseq.dir/build.make CMakeFiles/writeseq.dir/tests/writeseq.c.i
.PHONY : tests/writeseq.c.i

tests/writeseq.s: tests/writeseq.c.s
.PHONY : tests/writeseq.s

# target to generate assembly for a file
tests/writeseq.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/writeseq.dir/build.make CMakeFiles/writeseq.dir/tests/writeseq.c.s
.PHONY : tests/writeseq.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... check"
	@echo "... example"
	@echo "... perf"
	@echo "... shane"
	@echo "... shane1"
	@echo "... shane2"
	@echo "... streamvbyte"
	@echo "... streamvbyte_static"
	@echo "... unit"
	@echo "... writeseq"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... shane.o"
	@echo "... shane.i"
	@echo "... shane.s"
	@echo "... shane1.o"
	@echo "... shane1.i"
	@echo "... shane1.s"
	@echo "... shane2.o"
	@echo "... shane2.i"
	@echo "... shane2.s"
	@echo "... src/streamvbyte_0124_decode.o"
	@echo "... src/streamvbyte_0124_decode.i"
	@echo "... src/streamvbyte_0124_decode.s"
	@echo "... src/streamvbyte_0124_encode.o"
	@echo "... src/streamvbyte_0124_encode.i"
	@echo "... src/streamvbyte_0124_encode.s"
	@echo "... src/streamvbyte_decode.o"
	@echo "... src/streamvbyte_decode.i"
	@echo "... src/streamvbyte_decode.s"
	@echo "... src/streamvbyte_encode.o"
	@echo "... src/streamvbyte_encode.i"
	@echo "... src/streamvbyte_encode.s"
	@echo "... src/streamvbyte_zigzag.o"
	@echo "... src/streamvbyte_zigzag.i"
	@echo "... src/streamvbyte_zigzag.s"
	@echo "... src/streamvbytedelta_decode.o"
	@echo "... src/streamvbytedelta_decode.i"
	@echo "... src/streamvbytedelta_decode.s"
	@echo "... src/streamvbytedelta_encode.o"
	@echo "... src/streamvbytedelta_encode.i"
	@echo "... src/streamvbytedelta_encode.s"
	@echo "... tests/perf.o"
	@echo "... tests/perf.i"
	@echo "... tests/perf.s"
	@echo "... tests/unit.o"
	@echo "... tests/unit.i"
	@echo "... tests/unit.s"
	@echo "... tests/writeseq.o"
	@echo "... tests/writeseq.i"
	@echo "... tests/writeseq.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

